#!/usr/bin/env python3
"""Dependency license report and gate.

    pip install pip-licenses && (cd apps/web && npm ci)
    python scripts/license_report.py            # writes docs/dependency-licenses.md, exits 1 on a disallowed license
    python scripts/license_report.py --check    # gate only (CI)

Python: every distribution installed in the current environment (install apps/api/requirements.txt and
workers/python-sandbox/requirements.txt first). JavaScript: production dependencies of apps/web.
"""
from __future__ import annotations

import collections
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DISALLOWED = re.compile(r"\b(A?GPL|SSPL|BUSL|Commons Clause|Elastic License)\b", re.I)  # LGPL is reviewed case by case
REVIEW = re.compile(r"\b(LGPL|MPL|UNKNOWN|UNLICENSED|CUSTOM)\b", re.I)
OWN = {"isocline-api", "isocline-sdk", "@isocline/web"}
ALLOW = {  # reviewed exceptions: package -> reason
    "certifi": "MPL-2.0 (file-level copyleft that applies to modifications of its files); used unmodified as a CA bundle",
    "caniuse-lite": "CC-BY-4.0 browser-support data used at build time by browserslist; attribution preserved in the package",
}


def python_rows():
    out = subprocess.run([sys.executable, "-m", "piplicenses", "--from=mixed", "--format=json"], capture_output=True, text=True, check=True)
    return [(r["Name"], r["Version"], r["License"]) for r in json.loads(out.stdout) if r["Name"].lower() not in OWN]


def js_rows():
    out = subprocess.run(["npx", "--yes", "license-checker@25.0.1", "--production", "--json", "--excludePrivatePackages"],
                         cwd=ROOT / "apps/web", capture_output=True, text=True, check=True)
    rows = []
    for key, v in json.loads(out.stdout).items():
        name, _, ver = key.rpartition("@")
        lic = v.get("licenses")
        rows.append((name, ver, " OR ".join(lic) if isinstance(lic, list) else str(lic)))
    return rows


def main() -> int:
    py, js = python_rows(), js_rows()
    problems, review = [], []
    for eco, rows in (("python", py), ("npm", js)):
        for name, ver, lic in rows:
            if name in ALLOW:
                continue
            if DISALLOWED.search(lic) and not re.search(r"LGPL", lic, re.I):
                problems.append(f"{eco}: {name} {ver} ({lic})")
            elif REVIEW.search(lic):
                review.append(f"{eco}: {name} {ver} ({lic})")
    if "--check" not in sys.argv:
        lines = ["# Dependency licenses", "",
                 "Generated by `python scripts/license_report.py`. Isocline is licensed under Apache-2.0; dependencies are "
                 "used as unmodified packages and are not copied into this repository.", "",
                 f"- Python distributions (API, worker, sandbox controller, dev tools): {len(py)}",
                 f"- npm production packages (web UI): {len(js)}",
                 f"- Disallowed licenses (GPL/AGPL/SSPL/BUSL/Commons Clause/Elastic): {len(problems)}",
                 f"- Needing review (LGPL/MPL/unknown): {len(review)}", "", "## Reviewed exceptions", ""]
        lines += [f"- `{k}`: {v}" for k, v in ALLOW.items()] + ["", "## Summary by license", ""]
        for eco, rows in (("Python", py), ("npm", js)):
            c = collections.Counter(lic for _, _, lic in rows)
            lines += [f"### {eco}", "", "| License | Packages |", "|---|---|"] + [f"| {k} | {v} |" for k, v in c.most_common()] + [""]
        lines += ["## Sandbox runner image", "",
                  "`workers/python-sandbox/runner.Dockerfile` installs numpy, pandas, scipy (BSD-3-Clause) and matplotlib "
                  "(Matplotlib License, PSF-based) into the image user code runs in. They are not installed in the "
                  "environment this report scans; their licenses are permissive.", "",
                  "## Full list", "", "| Ecosystem | Package | Version | License |", "|---|---|---|---|"]
        lines += [f"| python | {n} | {v} | {l} |" for n, v, l in sorted(py, key=lambda r: r[0].lower())]
        lines += [f"| npm | {n} | {v} | {l} |" for n, v, l in sorted(js, key=lambda r: r[0].lower())]
        (ROOT / "docs/dependency-licenses.md").write_text("\n".join(lines) + "\n")
    for p in problems:
        print("DISALLOWED", p)
    for r in review:
        print("REVIEW", r)
    print(f"python={len(py)} npm={len(js)} disallowed={len(problems)} review={len(review)}")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
